# Generated by Django 3.1.7 on 2021-04-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('usr_email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('usr_password', models.CharField(max_length=200)),
                ('usr_name', models.CharField(max_length=200)),
                ('usr_age', models.IntegerField(default=0)),
                ('usr_sex', models.CharField(max_length=10)),
                ('usr_education', models.CharField(max_length=100)),
                ('usr_school', models.CharField(max_length=100)),
                ('usr_teaching_subjects', models.CharField(max_length=200)),
                ('usr_teaching_grade', models.CharField(max_length=200)),
                ('usr_experience', models.CharField(max_length=500)),
                ('usr_coin', models.IntegerField(default=0)),
                ('usr_credit', models.IntegerField(default=0)),
                ('usr_cookie', models.CharField(max_length=300)),
                ('usr_security_question1', models.CharField(max_length=200)),
                ('usr_security_question2', models.CharField(max_length=200)),
                ('usr_security_question3', models.CharField(max_length=200)),
                ('usr_sevurity_answer1', models.CharField(max_length=200)),
                ('usr_sevurity_answer2', models.CharField(max_length=200)),
                ('usr_sevurity_answer3', models.CharField(max_length=200)),
                ('usr_phone_number', models.IntegerField(max_length=11)),
            ],
        ),
    ]
