# Generated by Django 3.1.7 on 2021-04-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='usr_phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
