# Generated by Django 3.1.7 on 2021-04-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210406_0029'),
    ]

    operations = [
    ]
