# Generated by Django 3.1.7 on 2021-04-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210406_0038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Tabc',
        ),
    ]
