# Generated by Django 3.1.7 on 2021-04-05 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210406_0039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tabc',
            new_name='Table',
        ),
    ]
