# Generated by Django 3.1.7 on 2021-04-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210406_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='usr_cookie',
        ),
        migrations.AddField(
            model_name='table',
            name='usr_verify',
            field=models.IntegerField(default=0),
        ),
    ]
