# Generated by Django 3.1.7 on 2021-04-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_table_usr_password_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='usr_security_question1',
        ),
        migrations.RemoveField(
            model_name='table',
            name='usr_security_question2',
        ),
        migrations.RemoveField(
            model_name='table',
            name='usr_security_question3',
        ),
        migrations.RemoveField(
            model_name='table',
            name='usr_sevurity_answer1',
        ),
        migrations.RemoveField(
            model_name='table',
            name='usr_sevurity_answer2',
        ),
        migrations.RemoveField(
            model_name='table',
            name='usr_sevurity_answer3',
        ),
    ]
