# Generated by Django 3.1.7 on 2021-04-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210406_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='usr_password_verification_code',
        ),
    ]
