# Generated by Django 3.1.7 on 2021-04-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_table_usr_password_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='usr_coin',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='usr_credit',
            field=models.FloatField(default=0),
        ),
    ]
