# Generated by Django 3.1.7 on 2021-04-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210407_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='use_certificate_verufy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='use_graduation_certificate_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='table',
            name='usr_real_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
