# Generated by Django 3.1.7 on 2021-04-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210411_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='use_graduation_certificate_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='table',
            name='usr_real_name',
            field=models.CharField(max_length=100),
        ),
    ]
