# Generated by Django 3.1.7 on 2021-04-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20210411_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='usr_is_paid_fundteacher',
            field=models.IntegerField(default=0),
        ),
    ]
