# Generated by Django 3.1.7 on 2021-04-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_table_usr_is_paid_fundteacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='use_certificate_verufy',
            new_name='use_certificate_verify',
        ),
    ]
