# Generated by Django 3.1.7 on 2021-04-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_delete_evalu_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='usr_major',
            field=models.CharField(default='', max_length=100),
        ),
    ]
