# Generated by Django 3.1.7 on 2021-04-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_table_usr_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='usr_education',
        ),
    ]
