# Generated by Django 3.1.7 on 2021-05-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20210501_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='usr_now_City_County',
            new_name='usr_now_city_county',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='usr_real_City_County',
            new_name='usr_real_city_county',
        ),
    ]
