# Generated by Django 3.1.7 on 2021-05-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20210501_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='usr_identity_verify',
            field=models.IntegerField(default=0),
        ),
    ]
