# Generated by Django 3.1.7 on 2021-05-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_table_usr_account_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='usr_account_add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
