# Generated by Django 3.1.7 on 2021-06-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20210505_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='usr_head_img_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
