# Generated by Django 3.1.7 on 2021-06-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('order_token', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('usr_email', models.CharField(max_length=100)),
                ('coin_num', models.FloatField(default=0)),
                ('order_status', models.IntegerField(default=0)),
                ('order_start_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
