# Generated by Django 3.1.7 on 2021-04-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0002_auto_20210414_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='order_token',
            field=models.CharField(max_length=200),
        ),
    ]
