# Generated by Django 3.1.7 on 2021-05-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0003_auto_20210414_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='evaluate_score',
            field=models.FloatField(default=5),
        ),
    ]
