# Generated by Django 3.1.7 on 2021-05-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_user_world',
            name='global_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
