# Generated by Django 3.1.7 on 2021-05-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertize', '0002_auto_20210517_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table_user_world',
            old_name='global_name',
            new_name='map_name',
        ),
    ]
