# Generated by Django 3.1.7 on 2021-05-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='usr_identity_imgpath1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='table',
            name='usr_identity_imgpath2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='table',
            name='usr_identity_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='usr_student_imgpath1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='table',
            name='usr_student_imgpath2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='table',
            name='usr_student_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='usr_identity_imgurl1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='table',
            name='usr_identity_imgurl2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='table',
            name='usr_student_imgurl1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='table',
            name='usr_student_imgurl2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
