# Generated by Django 3.1.7 on 2021-05-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0002_auto_20210505_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='usr_identity_status',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='table',
            name='usr_student_status',
            field=models.IntegerField(default=3),
        ),
    ]
