# Generated by Django 3.1.7 on 2021-04-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('order_num', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('order_boos_email', models.CharField(max_length=200)),
                ('order_worker_email', models.CharField(default=None, max_length=200)),
                ('order_start_time', models.DateTimeField()),
                ('order_accept_time', models.DateTimeField()),
                ('order_complet_time', models.DateTimeField()),
                ('order_end_time', models.DateTimeField()),
                ('order_status', models.IntegerField(default=0)),
                ('order_is_worker_ask_complet', models.IntegerField(default=0)),
                ('order_is_boos_agree_complet', models.IntegerField(default=0)),
                ('order_is_worker_agree_refund', models.IntegerField(default=0)),
                ('order_refund_money', models.IntegerField(default=0)),
                ('order_teaching_grade', models.CharField(max_length=200)),
                ('order_teaching_subjects', models.CharField(max_length=200)),
                ('order_hourly_money', models.FloatField()),
                ('order_total_money', models.FloatField()),
                ('order_teaching_time', models.IntegerField()),
                ('order_boos_name', models.CharField(max_length=200)),
                ('order_boos_phone_number', models.CharField(max_length=11)),
                ('order_boos_qq_wei', models.CharField(max_length=200)),
                ('order_worker_name', models.CharField(max_length=200)),
                ('order_worker_phone_number', models.CharField(max_length=11)),
                ('order_worker_qq_wei', models.CharField(max_length=200)),
            ],
        ),
    ]
