# Generated by Django 3.1.7 on 2021-04-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='order_refund_money',
            field=models.FloatField(default=0),
        ),
    ]
