# Generated by Django 3.1.7 on 2021-04-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210407_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='order_boos_require',
            field=models.CharField(max_length=500),
        ),
    ]
