# Generated by Django 3.1.7 on 2021-04-07 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210407_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='order_num',
            new_name='order_token',
        ),
    ]
