# Generated by Django 3.1.7 on 2021-04-07 10:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210407_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='order_accept_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 10, 12, 56, 872644, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='table',
            name='order_complet_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 10, 12, 56, 872644, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='table',
            name='order_end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='order_start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
