# Generated by Django 3.1.7 on 2021-04-07 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210407_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='order_boos_email',
            new_name='order_boss_email',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='order_boos_name',
            new_name='order_boss_name',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='order_boos_phone_number',
            new_name='order_boss_phone_number',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='order_boos_qq_wei',
            new_name='order_boss_qq_wei',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='order_boos_require',
            new_name='order_boss_require',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='order_is_boos_agree_complet',
            new_name='order_is_boss_agree_complet',
        ),
        migrations.AlterField(
            model_name='table',
            name='order_accept_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 10, 23, 8, 257432, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='table',
            name='order_complet_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 10, 23, 8, 257432, tzinfo=utc)),
        ),
    ]
