# Generated by Django 3.1.7 on 2021-04-08 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210407_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('order_token', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('order_boss_email', models.CharField(max_length=200)),
                ('order_worker_email', models.CharField(max_length=200)),
                ('order_start_time', models.DateTimeField(auto_now_add=True)),
                ('order_accept_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_complet_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_end_time', models.DateTimeField(auto_now=True)),
                ('order_status', models.IntegerField(default=0)),
                ('order_is_worker_ask_complet', models.IntegerField(default=0)),
                ('order_is_boss_agree_complet', models.IntegerField(default=0)),
                ('order_is_worker_agree_refund', models.IntegerField(default=0)),
                ('order_refund_money', models.FloatField(default=0)),
                ('order_teaching_grade', models.CharField(max_length=200)),
                ('order_teaching_subjects', models.CharField(max_length=200)),
                ('order_hourly_money', models.FloatField()),
                ('order_teaching_time', models.IntegerField()),
                ('order_total_money', models.FloatField()),
                ('order_boss_name', models.CharField(max_length=200)),
                ('order_boss_phone_number', models.CharField(max_length=11)),
                ('order_boss_qq_wei', models.CharField(max_length=200)),
                ('order_boss_require', models.CharField(max_length=500)),
                ('order_worker_name', models.CharField(max_length=200)),
                ('order_worker_phone_number', models.CharField(max_length=11)),
                ('order_worker_qq_wei', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='table',
            name='order_accept_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='table',
            name='order_complet_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
