# Generated by Django 3.1.7 on 2021-04-09 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210408_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='order_is_boss_ask_refund',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table1',
            name='order_is_boss_ask_refund',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='table1',
            name='order_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
