# Generated by Django 3.1.7 on 2021-04-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210409_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='order_is_evalute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table1',
            name='order_is_evalute',
            field=models.IntegerField(default=0),
        ),
    ]
