# Generated by Django 3.1.7 on 2021-04-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210409_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='order_worker_earnest_money',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='table1',
            name='order_worker_earnest_money',
            field=models.FloatField(default=10),
        ),
    ]
