# Generated by Django 3.1.7 on 2021-04-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210409_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='order_refund_reason',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='table1',
            name='order_refund_reason',
            field=models.CharField(default='', max_length=500),
        ),
    ]
